import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      // The manifest is now generated by the plugin
      manifest: {
        name: 'Tech Carousel Creator',
        short_name: 'Tech Carousel AI',
        description: 'An AI-powered app to generate engaging carousel posts on technical topics.',
        theme_color: '#0f172a',
        background_color: '#0f172a',
        display: 'standalone',
        start_url: '.',
        icons: [
          {
            src: 'icon-192.png', // These files must be in the public folder
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any maskable',
          },
          {
            src: 'icon-512.png', // These files must be in the public folder
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any maskable',
          },
        ],
        shortcuts: [
          {
            name: 'Create New Carousel',
            short_name: 'New',
            description: 'Start a new carousel project',
            url: '/',
            icons: [{ "src": "/icon-192.png", "sizes": "192x192", "type": "image/png" }]
          }
        ]
      },
      // The plugin will generate a service worker automatically.
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png}'],
      }
    })
  ],
  define: {
    'process.env.API_KEY': JSON.stringify(process.env.API_KEY),
  },
});
